#!/bin/bash
#script to automatacally build and install apk from github projects, when you are in project directory

localf="./local.properties"
apk="./app/build/outputs/apk/app-debug.apk"
sdk="/home/rud/.Sdk"		#this should be absolute path name

function build { #this function builds and installs apk
	if [ ! -e "$apk" ]; then	#if apk exist then directly install it 
		if [ ! -e "./gradlew" ]; then	#check if inside valid gradle system
			echo no gradlew script found. not inside gradle system
			exit 1
		fi
		if [ ! -f "$localf" ]; then 
			echo 'sdk.dir='$sdk > $localf #for specifying location of sdk
			cat $localf && echo
		fi
		./gradlew app:assembleDebug			#if apk does not exist build it
	fi
	#adb connect 192.168.43.1:555  			#if you use adb wireless connection
	adb install -r $apk						#installs apk, reinstall if already exist
	#if apk cant be installed because no single adb device found then, connect to single adb and then rerun script
}

if [[ -z "$1" ]]; then
	build			#if no args passed then install the script
else				#if args is passed 
	if [[ $1 != http?(s)://github.com/* ]]; then
		echo "thats not github url"
		exit 1
	fi
	dir=$(echo $1 | sed 's@.*/@@')
	git clone $1 $dir 
	cd $dir
	build
	exit 1
fi

#if inside a gradle project then type "grdl" and it will build and install
#if you want to clone from github and then build and install then grdl <github url>
